#
# Module manifest for module 'module'
#
# Generated by: pwujczyk
#
# Generated on: 12/20/2019 11:36:26 AM
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ProductivityTools.ManageGitRepositories.psm1'

# Version number of this module.
ModuleVersion = '0.0.13'

# ID used to uniquely identify this module
GUID = '29befbab-71c7-422b-a837-e99303f08761'

# Author of this module
Author = 'Paweł Wujczyk'

# Company or vendor of this module
CompanyName = 'ProducvitityTools'

# Description of the functionality provided by this module
Description = 'It allows to publish multiple repositories to github'


# Functions to export from this module
FunctionsToExport = @(
	 'Push-GitRepository'
	,'Push-GitRepositories'
	,'Get-AutoCommitRepository'
	,'Get-AutoCommitRepositories'
	,'Pull-GitRepository'
	,'Pull-GitRepositories'
	,'Get-GitRepositoryStatus'
	,'Get-GitRepositoriesStatus',
    'Commit-GitRepositories'
    'Commit-GitRepository',
    'CommitPush-GitRepository',
    'CommitPush-GitRepositories')

PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Manage','Git','Repositories')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'http://productivitytools.tech/manage-git-repositories/'

        # A URL to an icon representing this module.
        IconUri = 'https://ptblogstorage.blob.core.windows.net/images/PT/ProductivityTools_blue_85px_4.png'

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable


# HelpInfo URI of this module
HelpInfoURI = 'http://productivitytools.tech/manage-git-repositories/'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

